version: '3.7'

services:
  nginx:
    container_name: yii_nginx
    image: nginx:latest
    ports:
      - "82:80"
    volumes:
      - ./www:/var/www
      - ./vhost.conf:/etc/nginx/conf.d/default.conf
    networks:
      - yii
    depends_on:
      - php

  php:
    container_name: yii_php
    build: ./images/php82fpm
    volumes:
      - ./www:/var/www
      - ./images/php82fpm/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./images/php82fpm/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    restart: always
    networks:
      - yii
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - postgresql

  postgresql:
    container_name: yii_postgresql
    image: postgres:latest
    volumes:
      - ./www:/var/www
      - ./postgresql-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "yii"
      POSTGRES_USER: "yii-postgres"
      POSTGRES_PASSWORD: "yii-postgres"
      PGDATA: "/var/lib/postgresql/data"
    restart: always
    networks:
      - yii

networks:
  yii:
    name: yii